### ISSUE TITLE
Can it hold connect pool with Redis?

### ISSUE THREAD

**Issue by coanor** [nrk/redis-lua#22]
I got a lot of Lua logic that need to write/read Redis in multiple thread(C call Lua). My original Redis-C client hold a connect pool with redis. Do I need the connect pool in redis-lua? or does the connect pool was required in redis-lua?

**Comment by nrk** [comment]
Sorry for the late response. This library does not implement any sort of connection pool, so you should handle such a case in you application logic if needed but keep in mind that redis-lua is not written with preemptive threading in mind.
