### ISSUE TITLE
is there a way to connect to specific db ?

### ISSUE THREAD

**Issue by VVhiteCoder** [nrk/redis-lua#37]

**Comment by ignacio** [comment]
I think you can't. You need to connect to a Redis instance and then select the db you want.

**Comment by nrk** [comment]
@VVhiteCoder just like @ignacio said, you can [`SELECT`](http://redis.io/commands/select) a specific database number after the connection to Redis has been established:

``` lua
local client = redis.connect(host, port)
client:select(database)
```

**Comment by VVhiteCoder** [comment]
Thanks, I know the select, but the question was about db param like in many other clients, but if select is the only way, it's ok :)
